import 'dart:async';
import '../../../../core/utils/logger.dart';
import '../../../../core/errors/exceptions.dart';
import '../../../../core/utils/result.dart';
import '../../../../core/utils/exception_mapper.dart';
import '../datasources/game_session_firestore_datasource.dart';
import '../models/game_session_model.dart';
import '../../domain/entities/game_session_entity.dart';
import 'game_state_sync_service.dart';

/// Host control service for managing game flow and host actions
/// Provides centralized control for game session hosting features
class HostControlService {
  final GameSessionFirestoreDataSource _dataSource;
  final GameStateSyncService _syncService;
  final Map<String, Timer> _phaseTimers = {};

  HostControlService({
    required GameSessionFirestoreDataSource dataSource,
    required GameStateSyncService syncService,
  }) : _dataSource = dataSource,
       _syncService = syncService;

  /// Create and host a new game session
  Future<Result<GameSessionEntity>> createGameSession({
    required String quizId,
    required String hostId,
    GameSessionSettings? settings,
  }) async {
    try {
      AppLogger.firebase(
        'HostControlService',
        'Creating game session for quiz: $quizId, host: $hostId',
      );

      final sessionEntity = GameSessionEntity(
        id: '', // Will be set by Firestore
        quizId: quizId,
        hostId: hostId,
        pin: '', // Will be generated by datasource
        status: GameSessionStatus.waiting,
        players: {},
        currentQuestionIndex: 0,
        createdAt: DateTime.now(),
        settings: settings,
      );

      final result = await _dataSource.createGameSession(
        sessionEntity.toModel(),
      );

      return result.when(
        success: (session) {
          AppLogger.firebase(
            'HostControlService',
            'Game session created: ${session.id} with PIN: ${session.pin}',
          );
          return Result.success(session.toEntity());
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error('Failed to create game session', e, stackTrace);
      return Result.failure(
        ServerException(
          message: 'Failed to create game session: ${e.toString()}',
          code: 'create_session_error',
        ).toFailure(),
      );
    }
  }

  /// Start game session with validation
  Future<Result<GameSessionEntity>> startGameSession({
    required String sessionId,
    required String hostId,
    int minPlayers = 1,
  }) async {
    try {
      // Validate host permissions and session state
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return await sessionResult.when(
        success: (session) async {
          // Validate host
          if (session.hostId != hostId) {
            return Result.failure(
              const UnauthorizedException(
                message: 'Only the host can start the game session',
              ).toFailure(),
            );
          }

          // Validate session state
          if (session.status != GameSessionStatus.waiting) {
            return Result.failure(
              const ValidationException(
                message: 'Game session must be in waiting state to start',
              ).toFailure(),
            );
          }

          // Check minimum players
          if (session.players.length < minPlayers) {
            return Result.failure(
              ValidationException(
                message: 'Need at least $minPlayers players to start the game',
              ).toFailure(),
            );
          }

          // Check if all players are ready (optional - can be configured)
          final unreadyPlayers = session.players.entries
              .where((entry) => !entry.value.isReady)
              .toList();

          if (unreadyPlayers.isNotEmpty) {
            final unreadyNames = unreadyPlayers
                .map((entry) => entry.value.name)
                .join(', ');
            return Result.failure(
              ValidationException(
                message: 'Waiting for players to be ready: $unreadyNames',
              ).toFailure(),
            );
          }

          // Start the game session
          final result = await _dataSource.startGameSession(sessionId);

          return result.when(
            success: (updatedSession) {
              AppLogger.firebase(
                'HostControlService',
                'Game session started: $sessionId with ${session.players.length} players',
              );

              // Initialize first question phase
              _scheduleQuestionPhase(
                sessionId: sessionId,
                questionIndex: 0,
                phase: 'display',
                durationSeconds: 10,
              );

              return Result.success(updatedSession.toEntity());
            },
            failure: (error) => Result.failure(error),
          );
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error(
        'Failed to start game session: $sessionId',
        e,
        stackTrace,
      );
      return Result.failure(
        ServerException(
          message: 'Failed to start game session: ${e.toString()}',
          code: 'start_session_error',
        ).toFailure(),
      );
    }
  }

  /// Advance to next question
  Future<Result<GameSessionEntity>> nextQuestion({
    required String sessionId,
    required String hostId,
    required int nextQuestionIndex,
    int displayDurationSeconds = 10,
    int answerDurationSeconds = 30,
  }) async {
    try {
      // Validate host permissions
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return await sessionResult.when(
        success: (session) async {
          if (session.hostId != hostId) {
            return Result.failure(
              const UnauthorizedException(
                message: 'Only the host can advance questions',
              ).toFailure(),
            );
          }

          if (session.status != GameSessionStatus.active) {
            return Result.failure(
              const ValidationException(
                message: 'Game session must be active to advance questions',
              ).toFailure(),
            );
          }

          // Update current question
          final result = await _dataSource.updateCurrentQuestion(
            sessionId,
            nextQuestionIndex,
          );

          return result.when(
            success: (updatedSession) {
              AppLogger.firebase(
                'HostControlService',
                'Advanced to question $nextQuestionIndex in session $sessionId',
              );

              // Schedule question phases
              _scheduleQuestionSequence(
                sessionId: sessionId,
                questionIndex: nextQuestionIndex,
                displayDuration: displayDurationSeconds,
                answerDuration: answerDurationSeconds,
              );

              return Result.success(updatedSession.toEntity());
            },
            failure: (error) => Result.failure(error),
          );
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error('Failed to advance question: $sessionId', e, stackTrace);
      return Result.failure(
        ServerException(
          message: 'Failed to advance question: ${e.toString()}',
          code: 'next_question_error',
        ).toFailure(),
      );
    }
  }

  /// End game session and calculate final scores
  Future<Result<GameSessionEntity>> endGameSession({
    required String sessionId,
    required String hostId,
  }) async {
    try {
      // Validate host permissions
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return await sessionResult.when(
        success: (session) async {
          if (session.hostId != hostId) {
            return Result.failure(
              const UnauthorizedException(
                message: 'Only the host can end the game session',
              ).toFailure(),
            );
          }

          // Complete the session
          final result = await _dataSource.completeGameSession(sessionId);

          return result.when(
            success: (completedSession) {
              AppLogger.firebase(
                'HostControlService',
                'Game session ended: $sessionId',
              );

              // Cancel any running phase timers
              _cancelPhaseTimers(sessionId);

              // Broadcast session end message
              _syncService.broadcastHostMessage(
                sessionId: sessionId,
                message: 'Game has ended! Check the final leaderboard.',
                messageType: 'game_ended',
              );

              return Result.success(completedSession.toEntity());
            },
            failure: (error) => Result.failure(error),
          );
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error('Failed to end game session: $sessionId', e, stackTrace);
      return Result.failure(
        ServerException(
          message: 'Failed to end game session: ${e.toString()}',
          code: 'end_session_error',
        ).toFailure(),
      );
    }
  }

  /// Pause game session
  Future<Result<void>> pauseGameSession({
    required String sessionId,
    required String hostId,
    String? reason,
  }) async {
    try {
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return await sessionResult.when(
        success: (session) async {
          if (session.hostId != hostId) {
            return Result.failure(
              const UnauthorizedException(
                message: 'Only the host can pause the game session',
              ).toFailure(),
            );
          }

          // Cancel current phase timers
          _cancelPhaseTimers(sessionId);

          // Update phase to paused
          await _syncService.updateGamePhase(
            sessionId: sessionId,
            questionIndex: session.currentQuestionIndex,
            phase: 'paused',
            phaseStartTime: DateTime.now(),
            phaseDurationSeconds: 0,
          );

          // Broadcast pause message
          await _syncService.broadcastHostMessage(
            sessionId: sessionId,
            message: reason ?? 'Game paused by host',
            messageType: 'game_paused',
          );

          AppLogger.firebase(
            'HostControlService',
            'Game session paused: $sessionId',
          );

          return const Result.success(null);
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error(
        'Failed to pause game session: $sessionId',
        e,
        stackTrace,
      );
      return Result.failure(
        ServerException(
          message: 'Failed to pause game session: ${e.toString()}',
          code: 'pause_session_error',
        ).toFailure(),
      );
    }
  }

  /// Resume game session
  Future<Result<void>> resumeGameSession({
    required String sessionId,
    required String hostId,
    int resumeCountdownSeconds = 5,
  }) async {
    try {
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return await sessionResult.when(
        success: (session) async {
          if (session.hostId != hostId) {
            return Result.failure(
              const UnauthorizedException(
                message: 'Only the host can resume the game session',
              ).toFailure(),
            );
          }

          // Broadcast resume countdown
          await _syncService.broadcastHostMessage(
            sessionId: sessionId,
            message: 'Game resuming in $resumeCountdownSeconds seconds...',
            messageType: 'game_resuming',
          );

          // Wait for countdown
          await Future.delayed(Duration(seconds: resumeCountdownSeconds));

          // Resume with active phase
          await _syncService.updateGamePhase(
            sessionId: sessionId,
            questionIndex: session.currentQuestionIndex,
            phase: 'active',
            phaseStartTime: DateTime.now(),
            phaseDurationSeconds: 30, // Default answer time
          );

          AppLogger.firebase(
            'HostControlService',
            'Game session resumed: $sessionId',
          );

          return const Result.success(null);
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error(
        'Failed to resume game session: $sessionId',
        e,
        stackTrace,
      );
      return Result.failure(
        ServerException(
          message: 'Failed to resume game session: ${e.toString()}',
          code: 'resume_session_error',
        ).toFailure(),
      );
    }
  }

  /// Skip current question
  Future<Result<void>> skipQuestion({
    required String sessionId,
    required String hostId,
    String? reason,
  }) async {
    try {
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return await sessionResult.when(
        success: (session) async {
          if (session.hostId != hostId) {
            return Result.failure(
              const UnauthorizedException(
                message: 'Only the host can skip questions',
              ).toFailure(),
            );
          }

          // Cancel current phase timers
          _cancelPhaseTimers(sessionId);

          // Advance to reveal phase immediately
          await _syncService.updateGamePhase(
            sessionId: sessionId,
            questionIndex: session.currentQuestionIndex,
            phase: 'skipped',
            phaseStartTime: DateTime.now(),
            phaseDurationSeconds: 5,
          );

          // Broadcast skip message
          await _syncService.broadcastHostMessage(
            sessionId: sessionId,
            message: reason ?? 'Question skipped by host',
            messageType: 'question_skipped',
          );

          AppLogger.firebase(
            'HostControlService',
            'Question skipped in session $sessionId: ${session.currentQuestionIndex}',
          );

          return const Result.success(null);
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error('Failed to skip question: $sessionId', e, stackTrace);
      return Result.failure(
        ServerException(
          message: 'Failed to skip question: ${e.toString()}',
          code: 'skip_question_error',
        ).toFailure(),
      );
    }
  }

  /// Get host control panel data
  Future<Result<HostDashboard>> getHostDashboard(String sessionId) async {
    try {
      final sessionResult = await _dataSource.getGameSessionById(sessionId);

      return sessionResult.when(
        success: (session) async {
          // Get question statistics if game is active
          Map<String, dynamic> questionStats = {};
          if (session.status == GameSessionStatus.active) {
            final statsResult = await _dataSource.getQuestionStatistics(
              sessionId: sessionId,
              questionIndex: session.currentQuestionIndex,
            );

            if (statsResult.isSuccess) {
              questionStats = statsResult.data!;
            }
          }

          final dashboard = HostDashboard(
            sessionId: sessionId,
            pin: session.pin,
            status: session.status,
            currentQuestionIndex: session.currentQuestionIndex,
            totalPlayers: session.players.length,
            readyPlayers: session.players.values.where((p) => p.isReady).length,
            questionStats: questionStats,
            topPlayers: _getTopPlayers(session.toEntity(), 5),
            canStart:
                session.status == GameSessionStatus.waiting &&
                session.players.isNotEmpty &&
                session.players.values.every((p) => p.isReady),
            canAdvance: session.status == GameSessionStatus.active,
          );

          return Result.success(dashboard);
        },
        failure: (error) => Result.failure(error),
      );
    } catch (e, stackTrace) {
      AppLogger.error(
        'Failed to get host dashboard: $sessionId',
        e,
        stackTrace,
      );
      return Result.failure(
        ServerException(
          message: 'Failed to get host dashboard: ${e.toString()}',
          code: 'get_dashboard_error',
        ).toFailure(),
      );
    }
  }

  /// Schedule question phase sequence automatically
  void _scheduleQuestionSequence({
    required String sessionId,
    required int questionIndex,
    required int displayDuration,
    required int answerDuration,
  }) {
    // Cancel existing timers for this session
    _cancelPhaseTimers(sessionId);

    var totalDelay = 0;

    // Phase 1: Display question
    _schedulePhaseTimer(
      sessionId,
      'display_$questionIndex',
      Duration(seconds: totalDelay),
      () => _syncService.updateGamePhase(
        sessionId: sessionId,
        questionIndex: questionIndex,
        phase: 'display',
        phaseStartTime: DateTime.now(),
        phaseDurationSeconds: displayDuration,
      ),
    );
    totalDelay += displayDuration;

    // Phase 2: Active answering
    _schedulePhaseTimer(
      sessionId,
      'active_$questionIndex',
      Duration(seconds: totalDelay),
      () => _syncService.updateGamePhase(
        sessionId: sessionId,
        questionIndex: questionIndex,
        phase: 'active',
        phaseStartTime: DateTime.now(),
        phaseDurationSeconds: answerDuration,
      ),
    );
    totalDelay += answerDuration;

    // Phase 3: Reveal answers
    _schedulePhaseTimer(
      sessionId,
      'reveal_$questionIndex',
      Duration(seconds: totalDelay),
      () => _syncService.updateGamePhase(
        sessionId: sessionId,
        questionIndex: questionIndex,
        phase: 'reveal',
        phaseStartTime: DateTime.now(),
        phaseDurationSeconds: 10,
      ),
    );
  }

  /// Schedule a single phase timer
  void _schedulePhaseTimer(
    String sessionId,
    String timerId,
    Duration delay,
    Future<void> Function() action,
  ) {
    final key = '${sessionId}_$timerId';

    _phaseTimers[key] = Timer(delay, () async {
      try {
        await action();
        _phaseTimers.remove(key);
      } catch (e) {
        AppLogger.error('Phase timer action failed: $key', e);
      }
    });
  }

  /// Schedule a single question phase
  void _scheduleQuestionPhase({
    required String sessionId,
    required int questionIndex,
    required String phase,
    required int durationSeconds,
  }) {
    Timer(Duration.zero, () async {
      try {
        await _syncService.updateGamePhase(
          sessionId: sessionId,
          questionIndex: questionIndex,
          phase: phase,
          phaseStartTime: DateTime.now(),
          phaseDurationSeconds: durationSeconds,
        );
      } catch (e) {
        AppLogger.error('Failed to schedule phase: $sessionId', e);
      }
    });
  }

  /// Cancel all phase timers for a session
  void _cancelPhaseTimers(String sessionId) {
    final keysToRemove = _phaseTimers.keys
        .where((key) => key.startsWith(sessionId))
        .toList();

    for (final key in keysToRemove) {
      _phaseTimers[key]?.cancel();
      _phaseTimers.remove(key);
    }

    AppLogger.firebase(
      'HostControlService',
      'Cancelled phase timers for: $sessionId',
    );
  }

  /// Get top players for dashboard
  List<PlayerInfo> _getTopPlayers(GameSessionEntity session, int count) {
    final sortedPlayers = session.players.entries.toList();
    sortedPlayers.sort((a, b) => b.value.score.compareTo(a.value.score));

    return sortedPlayers.take(count).map((entry) {
      return PlayerInfo(
        id: entry.key,
        name: entry.value.name,
        score: entry.value.score,
        isReady: entry.value.isReady,
        joinedAt: entry.value.joinedAt,
        answersCount: entry.value.answers.length,
        isOnline: true,
      );
    }).toList();
  }

  /// Cleanup all timers
  void dispose() {
    for (final timer in _phaseTimers.values) {
      timer.cancel();
    }
    _phaseTimers.clear();

    AppLogger.firebase(
      'HostControlService',
      'Disposed all host control timers',
    );
  }
}

/// Host dashboard data model
class HostDashboard {
  final String sessionId;
  final String pin;
  final GameSessionStatus status;
  final int currentQuestionIndex;
  final int totalPlayers;
  final int readyPlayers;
  final Map<String, dynamic> questionStats;
  final List<PlayerInfo> topPlayers;
  final bool canStart;
  final bool canAdvance;

  const HostDashboard({
    required this.sessionId,
    required this.pin,
    required this.status,
    required this.currentQuestionIndex,
    required this.totalPlayers,
    required this.readyPlayers,
    required this.questionStats,
    required this.topPlayers,
    required this.canStart,
    required this.canAdvance,
  });

  bool get allPlayersReady => totalPlayers > 0 && readyPlayers == totalPlayers;
  double get readyPercentage =>
      totalPlayers > 0 ? readyPlayers / totalPlayers : 0.0;
}

/// Player info for host dashboard
class PlayerInfo {
  final String id;
  final String name;
  final int score;
  final bool isReady;
  final DateTime joinedAt;
  final int answersCount;
  final bool isOnline;

  const PlayerInfo({
    required this.id,
    required this.name,
    required this.score,
    required this.isReady,
    required this.joinedAt,
    required this.answersCount,
    required this.isOnline,
  });
}
