import '../../../../core/utils/result.dart';
import '../../../../core/errors/failures.dart';
import '../entities/game_session_entity.dart';
import '../entities/game_pin.dart';
import '../repositories/game_session_repository.dart';

/// Use case for creating a new game session
/// Handles PIN generation and session initialization
class CreateGameSession {
  final GameSessionRepository _repository;

  const CreateGameSession(this._repository);

  Future<Result<GameSessionEntity>> call({
    required String quizId,
    required String hostId,
    GameSessionSettings? settings,
  }) async {
    try {
      // Generate unique PIN
      final pinResult = await _repository.generateUniquePin();
      
      if (pinResult.isFailure) {
        return Result.failure(pinResult.failureOrNull!);
      }

      final pin = pinResult.dataOrNull!;

      // Validate PIN format
      if (!GamePin.isValidPin(pin)) {
        return Result.failure(
          const Failure.validationFailure(
            message: 'Generated PIN is invalid',
          ),
        );
      }

      // Create session entity
      final session = GameSessionEntity(
        id: '', // Will be generated by Firestore
        quizId: quizId,
        hostId: hostId,
        pin: pin,
        status: GameSessionStatus.waiting,
        players: {},
        currentQuestionIndex: 0,
        createdAt: DateTime.now(),
        settings: settings ?? const GameSessionSettings(),
      );

      // Create session in repository
      final result = await _repository.createGameSession(session);

      if (result.isFailure) {
        return Result.failure(result.failureOrNull!);
      }

      // Validate created session
      final createdSession = result.dataOrNull!;
      if (!createdSession.isValid) {
        return Result.failure(
          const Failure.validationFailure(
            message: 'Created session is invalid',
          ),
        );
      }

      return Result.success(createdSession);
    } catch (e) {
      return Result.failure(
        Failure.serverFailure(
          message: 'Failed to create game session: ${e.toString()}',
          code: 'CREATE_SESSION_ERROR',
        ),
      );
    }
  }
}

/// Parameters for creating a game session
class CreateGameSessionParams {
  final String quizId;
  final String hostId;
  final GameSessionSettings? settings;

  const CreateGameSessionParams({
    required this.quizId,
    required this.hostId,
    this.settings,
  });
}