// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDJCmoAu-kYxA93ZtQZZ-4UFjsEUXW5JI',
    appId: '1:130579954244:web:273e08b8854d5891f91a11',
    messagingSenderId: '130579954244',
    projectId: 'quiz-app-1753821039',
    authDomain: 'quiz-app-1753821039.firebaseapp.com',
    storageBucket: 'quiz-app-1753821039.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv6bPsLKZ_8Rc2KdDblD2J7aKX3gXus-A',
    appId: '1:130579954244:android:9f0517b27f50a3b8f91a11',
    messagingSenderId: '130579954244',
    projectId: 'quiz-app-1753821039',
    storageBucket: 'quiz-app-1753821039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxqDm2ldQn6LKD_d7jmUX8j49jwBQ0fQA',
    appId: '1:130579954244:ios:c10a1ba68a363f00f91a11',
    messagingSenderId: '130579954244',
    projectId: 'quiz-app-1753821039',
    storageBucket: 'quiz-app-1753821039.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
