// Mocks generated by Mockito 5.4.6 from annotations
// in quiz_app/test/unit/features/authentication/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:quiz_app/core/utils/result.dart' as _i2;
import 'package:quiz_app/features/authentication/data/datasources/user_firestore_datasource.dart'
    as _i4;
import 'package:quiz_app/features/authentication/data/models/user_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserFirestoreDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFirestoreDataSource extends _i1.Mock
    implements _i4.UserFirestoreDataSource {
  MockUserFirestoreDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.Result<_i5.UserModel>> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i3.Future<_i2.Result<_i5.UserModel>>.value(
              _FakeResult_0<_i5.UserModel>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i2.Result<_i5.UserModel>> getUserByEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i3.Future<_i2.Result<_i5.UserModel>>.value(
              _FakeResult_0<_i5.UserModel>(
                this,
                Invocation.method(#getUserByEmail, [email]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i2.Result<_i5.UserModel>> createUser(_i5.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i3.Future<_i2.Result<_i5.UserModel>>.value(
              _FakeResult_0<_i5.UserModel>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i2.Result<_i5.UserModel>> updateUser(_i5.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<_i2.Result<_i5.UserModel>>.value(
              _FakeResult_0<_i5.UserModel>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i2.Result<void>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<void>>);

  @override
  _i3.Future<_i2.Result<bool>> userExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [userId]),
            returnValue: _i3.Future<_i2.Result<bool>>.value(
              _FakeResult_0<bool>(
                this,
                Invocation.method(#userExists, [userId]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<bool>>);

  @override
  _i3.Future<_i2.Result<List<_i5.UserModel>>> getUsersCreatedBetween(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersCreatedBetween, [startDate, endDate]),
            returnValue: _i3.Future<_i2.Result<List<_i5.UserModel>>>.value(
              _FakeResult_0<List<_i5.UserModel>>(
                this,
                Invocation.method(#getUsersCreatedBetween, [
                  startDate,
                  endDate,
                ]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<List<_i5.UserModel>>>);

  @override
  _i3.Future<_i2.Result<List<_i5.UserModel>>> searchUsersByName(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsersByName, [query]),
            returnValue: _i3.Future<_i2.Result<List<_i5.UserModel>>>.value(
              _FakeResult_0<List<_i5.UserModel>>(
                this,
                Invocation.method(#searchUsersByName, [query]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<List<_i5.UserModel>>>);

  @override
  _i3.Future<_i2.Result<List<_i5.UserModel>>> getTopUsersByScore(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getTopUsersByScore, [limit]),
            returnValue: _i3.Future<_i2.Result<List<_i5.UserModel>>>.value(
              _FakeResult_0<List<_i5.UserModel>>(
                this,
                Invocation.method(#getTopUsersByScore, [limit]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<List<_i5.UserModel>>>);

  @override
  _i3.Stream<_i2.Result<_i5.UserModel>> watchUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUser, [userId]),
            returnValue: _i3.Stream<_i2.Result<_i5.UserModel>>.empty(),
          )
          as _i3.Stream<_i2.Result<_i5.UserModel>>);

  @override
  _i3.Future<_i2.Result<void>> batchUpdateUsers(List<_i5.UserModel>? users) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateUsers, [users]),
            returnValue: _i3.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#batchUpdateUsers, [users]),
              ),
            ),
          )
          as _i3.Future<_i2.Result<void>>);

  @override
  _i3.Future<T> handleRemoteOperation<T>(_i3.Future<T> Function()? operation) =>
      (super.noSuchMethod(
            Invocation.method(#handleRemoteOperation, [operation]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#handleRemoteOperation, [operation]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#handleRemoteOperation, [operation]),
                ),
          )
          as _i3.Future<T>);
}
